apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: "chkyass/catalog-service:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /catalog/status
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 240
            timeoutSeconds: 120
          readinessProbe:
            httpGet:
              path: /catalog/status
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1