apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
        - name: data-service
          image: "chkyass/data-service:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8083
          livenessProbe:
            httpGet:
              path: /ratingsdata/status
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 240
            timeoutSeconds: 120
          readinessProbe:
            httpGet:
              path: /ratingsdata/status
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1