apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: info-service
  template:
    metadata:
      labels:
        app: info-service
    spec:
      containers:
        - name: info-service
          image: "chkyass/info-service:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8082
          livenessProbe:
            httpGet:
              path: /movies/status
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 240
            timeoutSeconds: 120
          readinessProbe:
            httpGet:
              path: /movies/status
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1